version: '3.1'

services:
  db:
    image: postgres:16
    platform: linux/arm64/v8
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data

volumes:
  my_db_volume:
